version: '3.4'
services:
  postgresql:
    image: postgres:15.2
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  s3:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - fs:/data
    env_file:
      - .env
    command: [server, /data, --console-address, ":9001"]

volumes:
  db:
  fs: